version: '3.8'

services:

  nest:
    container_name: nest
    build:
      context: requirements/nest
      dockerfile: Dockerfile
    volumes:
      - back:/app
    ports:
      - 3000:3000
      - 5555:5555
    env_file: .env
    networks:
      - inception
    depends_on:
      - postgresql

  front:
    container_name: front
    build:
      context: requirements/front
    ports:
      - "3002:5173"
    volumes:
      - front:/app
    networks:
      - inception
    env_file: .env
    depends_on:
      - nest

  postgresql:
    image: postgres:latest
    container_name: postgredb
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - inception
    env_file: .env

volumes:
  db-data:
  back:
      driver: local
      driver_opts:
        o: bind
        type: none
        device: "$PWD/srcs/requirements/nest/srcs"
  front:
      driver: local
      driver_opts:
        o: bind
        type: none
        device: "$PWD/srcs/requirements/front/srcs"
networks:
  inception:
    driver: bridge
